apiVersion: v1
kind: Service
metadata:
  name: reporting-engine-service
  namespace: reporting-engine
  labels:
    app: reporting-engine
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: reporting-engine
